package com.cmf.sale.entities;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
//@Entity
//@Table(name = "contact")
public class Contact implements java.io.Serializable {

	private int id;
	private String mailCustomer;
	private String content;
	private Date created;
	private Integer status;

	public Contact() {
	}

	public Contact(int id) {
		this.id = id;
	}

	public Contact(int id, String mailCustomer, String content, Date created, Integer status) {
		this.id = id;
		this.mailCustomer = mailCustomer;
		this.content = content;
		this.created = created;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "mail_customer", length = 250)
	public String getMailCustomer() {
		return this.mailCustomer;
	}

	public void setMailCustomer(String mailCustomer) {
		this.mailCustomer = mailCustomer;
	}

	@Column(name = "content", length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
