package com.cmf.sale.entities;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
//@Entity
//@Table(name = "invoice")
public class Invoice implements java.io.Serializable {
	private Integer id;
	private String nameCus;
	private String phoneCus;
	private String addressCus;
	private String noteCus;
	private Double total;
	private Date created;
	private Date updated;
	private Integer status;
	private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

	public Invoice() {
	}

	public Invoice(String nameCus, String phoneCus, String addressCus, String noteCus, Double total, Date created,
			Date updated, Integer status, Set<InvoiceDetail> invoiceDetails) {
		this.nameCus = nameCus;
		this.phoneCus = phoneCus;
		this.addressCus = addressCus;
		this.noteCus = noteCus;
		this.total = total;
		this.created = created;
		this.updated = updated;
		this.status = status;
		this.invoiceDetails = invoiceDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name_cus", length = 250)
	public String getNameCus() {
		return this.nameCus;
	}

	public void setNameCus(String nameCus) {
		this.nameCus = nameCus;
	}

	@Column(name = "phone_cus", length = 15)
	public String getPhoneCus() {
		return this.phoneCus;
	}

	public void setPhoneCus(String phoneCus) {
		this.phoneCus = phoneCus;
	}

	@Column(name = "address_cus", length = 500)
	public String getAddressCus() {
		return this.addressCus;
	}

	public void setAddressCus(String addressCus) {
		this.addressCus = addressCus;
	}

	@Column(name = "note_cus", length = 500)
	public String getNoteCus() {
		return this.noteCus;
	}

	public void setNoteCus(String noteCus) {
		this.noteCus = noteCus;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated", length = 19)
	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoice")
	public Set<InvoiceDetail> getInvoiceDetails() {
		return this.invoiceDetails;
	}

	public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
		this.invoiceDetails = invoiceDetails;
	}

}
