package com.cmf.sale.entities;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.google.gson.annotations.Expose;

/**
 * ProductType generated by hbm2java
 */
//@Entity
//@Table(name = "product_type")
public class ProductType implements java.io.Serializable {

	private int id;
	@Expose
	private String name;
	private Integer status;
	
	private Set<Product> products = new HashSet<Product>(0);

	public ProductType() {
	}

	public ProductType(int id) {
		this.id = id;
	}

	public ProductType(int id, String name, Integer status, Set<Product> products) {
		this.id = id;
		this.name = name;
		this.status = status;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productType")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
